### ISSUE TITLE
Camera Issues pulled from Cedric Chat

### ISSUE THREAD

**Issue by m-rufflesmcghie** [Motorola-Common/android_device_motorola_cedric#1]
[bugreport-cedric_retail-OPM2.171026.006.H1-2018-07-26-01-08-02.txt](https://github.com/Motorola-Common/android_device_motorola_cedric/files/2231146/bugreport-cedric_retail-OPM2.171026.006.H1-2018-07-26-01-08-02.txt)

[log.txt](https://github.com/Motorola-Common/android_device_motorola_cedric/files/2231184/log.txt)

Logs from Cedric Chat

**Comment by KalilDev** [comment]
Can you repost the issue with the logs on gist, and use the name template please?
