### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by SphericalKat** [Motorola-Common/android_device_motorola_cedric#2]
Gib volte thx

**Comment by SphericalKat** [comment]
@ATechnoHazard Well it works

**Comment by KalilDev** [comment]
Don't make the GitHub cancerous pls

**Comment by Dyneteve** [comment]
@ATechnoHazard When volit that's the next gen of volte

**Comment by KalilDev** [comment]
@Dyneteve Also stop messing my GitHub

**Comment by infixremix** [comment]
@Dyneteve you can't gban me here u wet bitch
