### ISSUE TITLE
Device still rebooting to recovery on android P s-GSI.

### ISSUE THREAD

**Issue by ayamdobhal** [Motorola-Common/android_device_motorola_cedric#3]
Even after the new fix. The device still reboots to recovery due to mobile network. If I use P without sim card, it works just fine. These logs were sent by Daniel S.
https://gist.github.com/m-rufflesmcghie/8fdf59ef11fb25b3df278ddc60e2d725

**Comment by m-rufflesmcghie** [comment]
Logs

https://gist.github.com/m-rufflesmcghie/8fdf59ef11fb25b3df278ddc60e2d725

**Comment by AyamDobhal** [comment]
@m-rufflesmcghie That's not the complete log either

**Comment by KalilDev** [comment]
not related to the Cedric treble rom + already fixed
