### ISSUE TITLE
08/12 Android-P sGSI: FM Radio Not Working

### ISSUE THREAD

**Issue by m-rufflesmcghie** [Motorola-Common/android_device_motorola_cedric#5]
Expected Behavior
Radio should work as expected

Actual Behavior
Error "Currently Not Available"

Steps to Reproduce the Problem
1- Headphones plugged in
2- Launch Radio App

Log Link :- https://gist.github.com/kutlay1653/1eb9bbb32df554ece1e44619b42a9011

Note :- Have screenshot and I have done basic troubleshooting.

**Comment by m-rufflesmcghie** [comment]
@m-rufflesmcghie @pedrokalil can't do colour formatting on my phone but everything is their as requested in template form

**Comment by infixremix** [comment]
@m-rufflesmcghie Your mum gay lol

**Comment by p8tgames** [comment]
@m-rufflesmcghie Yikes

**Comment by p8tgames** [comment]
@p8tgames Oof this is so sad

**Comment by KalilDev** [comment]
@infixremix @infixremix stop being a fucking kid and spamming my GitHub

**Comment by p8tgames** [comment]
@KalilDev :(

**Comment by mat1jaczyyy** [comment]
stop meming and start fixing

**Comment by KalilDev** [comment]
will be looked in after the common trees redo and the unification with potter

**Comment by kutlay1653** [comment]
This fix works but maybe getting libfmjni.so from an arm64 rom it will better 
When I use fix radio works but sound increasing and decreasing immediately radio can listanable
[Potter fm fix](https://potterroms.me/Mods/FMRadio.zip)

**Comment by jibnew** [comment]
@kutlay1653 
> This fix works but maybe getting libfmjni.so from an arm64 rom it will better
> When I use fix radio works but sound increasing and decreasing immediately radio can listanable
> [Potter fm fix](https://potterroms.me/Mods/FMRadio.zip)

Thanks! Works well but sound is unstable.

**Comment by KalilDev** [comment]
deprecated
