### ISSUE TITLE
13/12 Android-P sGSI: CamREC not Working

### ISSUE THREAD

**Issue by GodZlayer** [Motorola-Common/android_device_motorola_cedric#6]
Expected Behavior
Camera recorder should work as expected

Actual Behavior
Stops working and freezing time count

Steps to Reproduce the Problem
1- start any camera app ( wpp and instagram don't work too )
2- Recording mode and try

Log Link : https://gist.github.com/GodZlayer/ab2d84b4eaddf4efa4e37be2aabe1106
[log.txt](https://github.com/Motorola-Common/android_device_motorola_cedric/files/2285275/log.txt)

Note : Any app will crash when start to record

**Comment by KalilDev** [comment]
log isnt on gist

**Comment by GodZlayer** [comment]
sorry, i send now.

**Comment by KalilDev** [comment]
@GodZlayer no problem, follow my template and ill look into it
