### ISSUE TITLE
Volte

### ISSUE THREAD

**Issue by adhilrahman** [Motorola-Common/android_device_motorola_cedric#7]
As almost all devices are getting volte fix in android p gsi rom. Would request a volte fix

**Comment by SphericalKat** [comment]
Never.

**Comment by raphielscape** [comment]
LMAO

**Comment by Blacksuan19** [comment]
Nani

**Comment by kutlay1653** [comment]
@kalildev will f*ck you

**Comment by KalilDev** [comment]
Fuck you and this volte BS. Also stop spamming XDA......

**Comment by kutlay1653** [comment]
volte

**Comment by kutlay1653** [comment]
lol i just trolled
