### ISSUE TITLE
LineageTreble20170723: Phh-treble107: bootloop

### ISSUE THREAD

**Issue by jibnew** [Motorola-Common/android_device_motorola_cedric#8]
@KalilDev 

Bootloop - reaches main screen, then restarts immediately.

[Logcat on gist](https://gist.github.com/jibnew/2a63accd48fc9adbf4dca4c9e3441951#file-lineage20170723phh-treble107-log)

**Comment by kutlay1653** [comment]
as i know as he wont develop device again

**Comment by jibnew** [comment]
@kutlay1653 Too bad. Maybe you know which pie gsi works with cedric?

**Comment by kutlay1653** [comment]
sgsi works but some devs working for all gsis as i know as

**Comment by jibnew** [comment]
@kutlay1653 Thanks! Will try sgsi then. Are any others working specifically for cedric?

**Comment by kutlay1653** [comment]
i dunno but i can confirm pr1-2 boots well

**Comment by jibnew** [comment]
@kutlay1653 

> i dunno but i can confirm pr1-2 boots well

For pr1 I found [P-PR1-sGSI-Aonly.zip](https://androidfilehost.com/?w=search&s=P-PR1-sGSI-Aonly.zip) by erfanoabdi, is this what you mean? Could not find any pr1-2 or pr2 for that matter

**Comment by kutlay1653** [comment]
https://forum.xda-developers.com/project-treble/trebleenabled-device-development-a-only-roms/ported-p-sgsi-pr2-t3845789 @jbnew

**Comment by jibnew** [comment]
@kutlay1653 

> https://forum.xda-developers.com/project-treble/trebleenabled-device-development-a-only-roms/ported-p-sgsi-pr2-t3845789 @Jbnew

Thank you! Do you know if I also have to flash in the end the cedric post-sGSI zip as described in

https://forum.xda-developers.com/g5/development/treble-how-to-install-android-p-sgsi-t3823969

or not?

**Comment by KalilDev** [comment]
this is not the place for this kind of question+this shit is deprecated. gtfo of my github please
